# 	      .__                      .__  __    __          
#	_____  |  | _____    ___________|__|/  |__/  |_ ___.__.
#	\__  \ |  | \__  \ _/ ___\_  __ \  \   __\   __<   |  |
#	 / __ \|  |__/ __ \\  \___|  | \/  ||  |  |  |  \___  |
#	(____  /____(____  /\___  >__|  |__||__|  |__|  / ____|
#	     \/          \/     \/                      \/     
#	

background_opacity: 0.95

# Fonts

font:
  normal: 
    family: FiraCode Nerd Font Mono 
    style: Regular

  bold:
    family: FiraCode Nerd Font Mono
    style: bold

  Light,Regular:
    family: FiraCode NF
    style: Light,Regular

  Medium,Regular:
    family: FiraCode Nerd Font Mono
    style: Medium,Regular
       
  size: 11

# Draw
draw_bold_text_with_bright_colors: true

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x1d2021'
    # soft contrast: background = '0x32302f '
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'