# 	      .__                      .__  __    __          
#	_____  |  | _____    ___________|__|/  |__/  |_ ___.__.
#	\__  \ |  | \__  \ _/ ___\_  __ \  \   __\   __<   |  |
#	 / __ \|  |__/ __ \\  \___|  | \/  ||  |  |  |  \___  |
#	(____  /____(____  /\___  >__|  |__||__|  |__|  / ____|
#	     \/          \/     \/                      \/     
#	

background_opacity: 0.94

# Fonts

font:
  normal: 
    family: FiraCode Nerd Font Mono 
    style: Regular

  bold:
    family: FiraCode Nerd Font Mono
    style: bold

  Light,Regular:
    family: FiraCode NF
    style: Light,Regular

  Medium,Regular:
    family: FiraCode Nerd Font Mono
    style: Medium,Regular
       
  size: 11

# Draw
draw_bold_text_with_bright_colors: true

# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x0f0f0f'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'