#!/bin/sh

## Get current keyboard layout in swaywm for waybar

swaymsg -t get_inputs | grep -m1 "xkb_active_layout_name" |  grep -m1 "xkb_active_layout_name" | sed  -e "s/.*(//" -e "s/).*//" -e "s/Latin American/LAT/" -e "s/.*US, intl.*/US,int/"

