# 	      .__                      .__  __    __
#	_____  |  | _____    ___________|__|/  |__/  |_ ___.__.
#	\__  \ |  | \__  \ _/ ___\_  __ \  \   __\   __<   |  |
#	 / __ \|  |__/ __ \\  \___|  | \/  ||  |  |  |  \___  |
#	(____  /____(____  /\___  >__|  |__||__|  |__|  / ____|
#	     \/          \/     \/                      \/
#

background_opacity: 0.94

# Fonts

font:
  normal:
    family: FiraCode Nerd Font Mono
    style: Regular

  bold:
    family: FiraCode Nerd Font Mono
    style: bold

  Light,Regular:
    family: FiraCode NF
    style: Light,Regular

  Medium,Regular:
    family: FiraCode Nerd Font Mono
    style: Medium,Regular

  size: 11

# Draw
draw_bold_text_with_bright_colors: true







# Colors (Pencil Light)
colors:
  # Default Colors
  primary:
    background: '0xf1f1f1'
    foreground: '0x424242'
  # Normal colors
  normal:
    black:   '0xE0D9D6'
    red:     '0xc30771'
    green:   '0x289f77'
    yellow:  '0xa89c14'
    blue:    '0x008ec4'
    magenta: '0x523c79'
    cyan:    '0x20a5ba'
    white:   '0xe0e0e0'
  # Bright colors
  bright:
    black:   '0x212121'
    red:     '0xfb007a'
    green:   '0x289f77'
    yellow:  '0x615900'
    blue:    '0x04adf6'
    magenta: '0x6855de'
    cyan:    '0x4fb8cc'
    white:   '0xf1f1f1'
